### PR TITLE
Added delayOnElement.includeHidden option

### PR DESCRIPTION
**Pull request by lukaszmn**

### CODE REVIEW

**Comment by IGreatlyDislikeJavascript** [comment]
Hi, thanks for your contribution. This is a great pull request.

One thing, you've named your option options.delayOnElement._includeHidden_, however I think this name is a little confusing as it's not a hidden element option - your code handles cases where the specified element hasn't actually been created in the DOM yet. 

In fact as I consider this, I think we should use your behavior as the default approach. To the implementor of a tour, does it matter if the element is hidden or not yet created...

Should Tourist default approach be to handle hidden and non-existent elements exactly the same when delayOnElement is specified?

We could easily do that by simply removing the the if() line on line 1418 (your fork) so that the code in the if clause is always executed, and then remove the else clause and the debug message on line 1455+.

That would implement your change as the default approach, which I think is more coder friendly.

What do you think?

**Comment by ibastevan** [comment]
This was just what i needed to fix my problem with my ajax modals, defo think it should be default approach!

**Comment by lukaszmn** [comment]
Hi, thanks for the feedback. I made that behavior the default one and I removed that option.

**Comment by lukaszmn** [comment]
Hi @IGreatlyDislikeJavascript, I just wanted to know when you are going to release a new version to NPM. I'm going to switch my dependencies to NPM but only after this one is up to date. Thanks.

**Comment by IGreatlyDislikeJavascript** [comment]
Hi @lukaszmn , I'll release the current repo version (with your fix) to NPM tomorrow, would that help?

**Comment by lukaszmn** [comment]
That's great, thank you.

**Comment by IGreatlyDislikeJavascript** [comment]
Published v0.2.1 to NPM now, which includes your fix. Please let me know if any problems.

Thanks for your contribution and support!

**Pull request merged**
