### PR TITLE
Added Reflex option

### PR DESCRIPTION
**Pull request by thenewbeat**
When a step uses backdrop and `reflex: false` then interactions with the element are intentionally blocked.

Leaving reflex undefined still produces the default behavior.

### CODE REVIEW

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for splitting out your pull and your contributions!

I'm not in front of my desktop right now so can't investigate this, but please could you explain the bug in more detail? I'm not sure where it manifests.

There are 3 options related to step element interaction behavior:

reflex: basically allows a click on the step's element to emulate a click on the "next step" button

reflexOnly: to move to the next tour step you must click the element, there is no "next step" button in the pop over

preventInteraction: prevents any clicking on or usage of the step element, and only an explicit click on tour popover "next" button will move the tour on.

Please could you let me know what behavior you're seeing, versus what would happen, versus the three options above? Thanks!

**Comment by thenewbeat** [comment]
Wow, I didn't know `preventInteraction` existed... Sorry, I was referencing the original docs instead of the comments in the JS file.

**Comment by IGreatlyDislikeJavascript** [comment]
No worries! I know that the documentation situtation is not ideal, and having to use the original Tour docs then read through the .js comments isn't the easiest. Hopefully someone will want to fix that for me, as writing lots of nice docs and putting a webpage together isn't really my thing!

I'll leave this pull request untouched for now. But if you wouldn't mind submitting a pull that fixes the backdrop problem you found, that would be appreciated.

Thanks!

**Comment by thenewbeat** [comment]
I've submitted the pull request to fix the backdrop issue. I'll close this pull request as it's not needed.

**Pull request closed without merging**
