### PR TITLE
Added support for changing button texts

### PR DESCRIPTION
**Pull request by vneri**
Hi, thank you for this fork!
I've added an option to the tour, so that the texts of the buttons can be modified (e.g. for localization).
You can now use the following in the Tour parameter (single textes can also be omitted):
```
buttonTexts{
  nextButton:"Go on",
  prevButton:"Go back",
  pauseButton:"Wait a sec",
  resumeButton:"Continue",
  endTourButton:"It's over",
}
```

Let me know what you think... Thanks

### CODE REVIEW

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for your contribution, I like it. It also raises a new question about how we do localization for the entire plugin.

I have just one suggestion - should we change the options object to inside .localization, or similar, rather than just buttonTexts? That will be a little more future proofed and allow us to add more localization later which is neatly inside a single object, rather than expanding the options object, if other features with default text are added to Tourist. For example:

`prevButton: this._options.localization.buttonTexts.prevButton||"Prev",`
`somethingElse: this._options.localization.divTexts.someMessageDiv||"Some future feature",`

That way we could add simple code in future to load a localization .js, which simply copies an object into .options, instead of needing to double merge the .options (there's other $.merges happening elsewhere in the code).

Also, just a minor english/consistency point, objTemplatesButton**Textes** should be objTemplatesButton**Texts**

Finally we'll need to add a note to the docs that this localization option will of course be overridden if a custom template is used.

Please let me know your thoughts. Thank you!

**Comment by vneri** [comment]
Hi great feedback, just added the changes and updated the documentation.
Let me know what you think...
Thanks!

**Comment by vneri** [comment]
Just saw that there is a label option?
https://gist.github.com/emayk/5384683

**Comment by IGreatlyDislikeJavascript** [comment]
Thanks for your updates, those changes look good and I'm very happy to merge them. I'll also duplicate your readme changes into the docs comments at the top of the .js as well, so there's consistency between readme and .js comments (although perhaps at some point soon it might become more sensible to only maintain the readme, as the comment at the top of the js is becoming huge!).

Thanks for your contribution!

> Just saw that there is a label option?

Looking at the date of that gist (6 years ago), I'm guessing that some previous version of Bootstrap Tour did have a label option. However I guarantee that most recent/current version of Bootstrap Tour - from which Tourist is forked - definitely doesn't have a label option! It must have been removed by sorich87, I don't know when though. It's good that you've added it back :-)

So don't worry, your work is definitely a valuable addition!

**Pull request merged**
